config-version = 1

[server]
host = "127.0.0.1"
port = 7070
log-level = "info"
log-file = "./logs/konkin.log"
log-rotate-max-size-mb = 10

[database]
url = "jdbc:h2:./data/konkin;AUTO_SERVER=TRUE"
user = "sa"
password = "sa"
pool-size = 5

[auth_queue]
enabled = true

[auth_queue.password-protection]
enabled = true
# rotate keys by deleting the referenced file
password-file = "./secrets/auth_queue.password"

[web-ui]
enabled = true

[web-ui.password-protection]
enabled = true
# rotate keys by deleting the referenced file
password-file = "./secrets/web-ui.password"

[web-ui.template]
directory = "./src/main/resources/templates"
name = "landing.ftl"

[web-ui.static]
directory = "./src/main/resources/static"
hosted-path = "/assets"

[web-ui.auto-reload]
enabled = true
assets-enabled = true

[debug]
enabled = true
seed-fake-data = true

[telegram]
enabled = true
secret-file = "./secrets/telegram.secret"
api-base-url = "https://api.telegram.org"

[coins.bitcoin]
enabled = true

[coins.bitcoin.secret-files]
# files are auto-generated on startup when missing
bitcoin-daemon-config-file = "./secrets/bitcoin-daemon.conf"
bitcoin-wallet-config-file = "./secrets/bitcoin-wallet.conf"

[coins.bitcoin.auth]
web-ui = true
rest-api = true
telegram = true
# unique identifier for agent MCP HTTP SSE connection
mcp = "agent-default"

[[coins.bitcoin.auth.auto-accept]]
[coins.bitcoin.auth.auto-accept.criteria]
type = "value-lt"
value = 0.01

[[coins.bitcoin.auth.auto-accept]]
[coins.bitcoin.auth.auto-accept.criteria]
type = "cumulated-value-lt"
value = 0.6
period = "PT24H" #ISO-8601 duration

[[coins.bitcoin.auth.auto-deny]]
[coins.bitcoin.auth.auto-deny.criteria]
type = "value-gt"
value = 1.0

[[coins.bitcoin.auth.auto-deny]]
[coins.bitcoin.auth.auto-deny.criteria]
type = "cumulated-value-gt"
value = 1.0
period = "PT24H" #ISO-8601 duration
